version: "3"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynetwork
  jenkins:
     image: jenkins/jenkins:2.277.4-jdk11
    ports:
      - 9002:9002
    networks:
      - mynetwork
networks:
  mynetwork:
